USE WAREHOUSE HACKWAREHOUSE1;
CREATE DATABASE IF NOT EXISTS HACKGT;
CREATE SCHEMA  IF NOT EXISTS HACKGT.RAW;
CREATE TABLE IF NOT EXISTS HACKGT.RAW.BRACE_SENSOR_READINGS (
  session_id   VARCHAR,
  device_id    VARCHAR,
  server_ts    TIMESTAMP_NTZ,
  device_ts_ms BIGINT,
  angle        DOUBLE,
  raw_adc      INTEGER,
  sample_seq   INTEGER,
  raw          VARIANT
);
